### ISSUE TITLE
Error when saving routes

### ISSUE THREAD

**Issue by AaskovKnudsen** [wellenvogel/BonjourBrowser#11]
I am using the BonjourBrowser ver. 1.13 for android 14 on a Samsung Tab S9FE device.
I use it for avNav, newest version on RPI4.
I want to save a route to the default android download folder.

Hitting the save botton, I get this error message and the file is not saved:

targeting s+ (version 31 and above) requires that one of flag_immutable unity

What can be wrong?

IF I use Samsung Internet Browser, it it working OK.

**Comment by wellenvogel** [comment]
yes, have to adapt bonjourBrowser to the newest android requirements.
For now you need to go for the workaround with another browser for saving data.

**Comment by AaskovKnudsen** [comment]
No problem.
Thank you for replying.
Regards Jan

**Comment by wellenvogel** [comment]
Just uploaded 1.14 to the store - can potentially take some time until google releases it.

**Comment by AaskovKnudsen** [comment]
Hi Andreas
I now installed 1.14
Download is now working in android 14.
Thank you for helping.
Regards Jan

**Comment by wellenvogel** [comment]
Good to know ;-)
