### ISSUE TITLE
Alternative APK-Download

### ISSUE THREAD

**Issue by IzzySoft** [wellenvogel/BonjourBrowser#2]
Would you consider making the app available outside of Play Store – e.g. by attaching the APK to their tags/releases here at Github, or even bringing the app to [F-Droid](https://f-droid.org/)? Thanks in advance!

**Comment by wellenvogel** [comment]
ok, did this - see https://github.com/wellenvogel/BonjourBrowser/releases

**Comment by IzzySoft** [comment]
Thanks a lot! Do you wish to try for an F-Droid listing then? To simply pick it for my repo, it would need the APK file attached directly (not as ZIP); that can be done via the big gray areay below the textbox when editing a release (i.e. the second one labeled "Attach binaries by dropping them here or selecting them" IIRC – it's a bit confusing that they have two such areas; and as I've heard one of the two is not accepting APKs but the other one is). The file then turns up next to the source ZIP & Tarball instead of inside the description.

**Comment by wellenvogel** [comment]
Surprising...
Did it like you proposed - and it worked :-)
An F-Droid listing would be ok for me.

**Comment by wellenvogel** [comment]
just added a license.txt - it is MIT.

**Comment by IzzySoft** [comment]
Thanks a lot! Find it [here](https://apt.izzysoft.de/fdroid/index/apk/de.wellenvogel.bonjourbrowser) in about 5 hours (that is my repo). I gladly assist with inclusion at F-Droid.org – but for that I'd fist need a little clarification on

> add proprietary js api to dim the screen (7a2202b)

While in my repo, minor proprietary components are tolerated (with the goal to get things started and the hope for a clean-up, so the app then becomes "fully FLOSS" and can apply for inclusion at F-Droid.org), for F-Droid.org itself that's a show-stopper *if included directly.* If OTOH it's something the user can "load optionally", in the worst case that means the NonFreeAdd AntiFeature.

I'm no Java dev, but from skimming over that commit I guess you might have meant "appropriate" (fitting/"passend") instead of "proprietary" ("proprietär", not FLOSS)? If you can confirm this:

* I'd prepare a PR for your app to add a (basic) "starter kit" for [Fastlane structures](https://gitlab.com/snippets/1895688) (F-Droid will want this – and even I'd prefer to have them with your repo, so you can adjust e.g. the app description whenever you feel it needed, and our updaters would fetch that together with each new release) – this I could do in any case, even if my above guess was wrong
* that merged, I'd open a [RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging) for you, linking here for reference that you are fine with this
* that RFP will then be processed, resulting in the metadata being merged at F-Droid.org and the app being built there from source and finally appear in the "catalog"
* once it's up and available at F-Droid for about a week, I'd remove it again from my repo (unless you wish it to stay there) – mainly to avoid confusion and "duplicate listings". Pros for my repo are faster updates – pros for F-Droid are higher trust (to name the main points).

And thanks for marking the license!

**Comment by wellenvogel** [comment]
The term "proprietary" more or less is correct - but it does not violate the FLOSS principle. It's just that it is proprietary for the app - i.e. if someone would like to use it they would need to really build something specifically...
It is still completely open.
If you have a proposal for a better wording...
At the end I'm not willing to invest a lot of work to make it fit for F-Droid. 
If it can be done with minor efforts - great (a PR from your side is ok anyway for that - or just creating a file for a release..).

**Comment by IzzySoft** [comment]
"proprietary": I'd simply call it "specific" then. OK, it's just a commit message I accidentally stumbled upon – so if someone asks, now I know how it's meant, thanks!

> I'm not willing to invest a lot of work to make it fit for F-Droid.

I don't expect that will be needed, apart from merging my PR which I will prepare now. Packagers might need a little hint or not, that I cannot tell. If it looks like too much, we can still withdraw.

> or just creating a file for a release

Yes please: as long as it's in my Repo, that would be the APK – for F-Droid, it could be the per-release changelog in Fastlane (though I'd welcome that as well).

OK, let's go for it then. In a couple of minutes, you'll find my PR here. Thanks a lot!!!
