### ISSUE TITLE
Fastlane broken

### ISSUE THREAD

**Issue by linsui** [wellenvogel/BonjourBrowser#5]
See https://gitlab.com/snippets/1895688 , chongelogs should live in a subdir. Looks like f-droid can't handle it well so that no metadata is fetched.

Please fix it, thanks!

**Comment by wellenvogel** [comment]
fiexed with 1.11

**Comment by linsui** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Will you make a new release soon? Because currently, your app shows up without summary, description etc at F-Droid (due to the broken Fastlane at the time of the last release).

**Comment by wellenvogel** [comment]
just forgot the tag... - pushed right now

**Comment by IzzySoft** [comment]
Great, thanks a lot! Should be in the next build cycle then – which with any luck will start within the next 24h.
