### ISSUE TITLE
Android 11 compatible? - app probably requires Multicast_Receive permission 

### ISSUE THREAD

**Issue by Catfriend1** [wellenvogel/BonjourBrowser#6]
Hi,

I'd just like to ask if you already have feedback or verified that the app still works fine on Android 11. We've recently had problems with our "local discovery by receiving multicast beacons" here at the Syncthing-Android project and I've found out that Android 11 restricts apps from sending multicast beacons. BUT: receiving multicast packets - like they also exist for Bonjour - requires a permission the apps needs to ask for and hold a so called MulticastLock first before starting to listen.

Please see my PR containing the changes I've made at Syncthing-Android to support receiving multicast on Android 11. Feel free to take any code if helpful. ( https://github.com/Catfriend1/syncthing-android/pull/800 )

Thank you.

Kind regards,
Catfriend1

**Comment by wellenvogel** [comment]
Hi,
Many thanks for this hint.
Until now I did not test on Android 11 - but I will have a look...
Regards
Andreas

**Comment by wellenvogel** [comment]
Looking at the issue there is a chance that BonjourBrowser will not run into this one. At least as long as the first step of mdns service discovery still works on android ( BonjourBrowser is using the Android service).
For all stuff that I do directly inside BonjourBrowser I do not use multicast but pure UDP unicast.
But I have to test...

**Comment by wellenvogel** [comment]
Ok, after some testing - it runs without problems on Android 11 (as mentioned - I do not use Multicast in the app directly).
Anyway many thanks for pointing to the problem.

**Comment by ghost** [comment]
please delete issue
