### ISSUE TITLE
Maybe you could add ip gateway subnet info

### ISSUE THREAD

**Issue by ldijkman** [wellenvogel/BonjourBrowser#8]
Maybe you could add
Phone connected Network info
ip 
gateway ip
subnetmask ip

That would be nice

https://github.com/ldijkman/randomnerd_esp32_wifi_manager

**Comment by wellenvogel** [comment]
Basically this could be done. But it would not really fit to the use case of the BonjourBrowser.
What would you like to achieve by knowing this info?
And if there were more nets - which one to show?

**Comment by wellenvogel** [comment]
closing this due to no answer
